apiVersion: apps/v1
kind: Deployment
metadata:
  name: schildichat-web
spec:
  template:
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: schildichat-web
      containers:
        - name: common
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.json
              subPath: config.json
