
stages:
  - test
  - build
  - build-web
  - deploy

default:
  interruptible:                   true
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - api_failure

variables:
  GIT_SUBMODULE_STRATEGY:          recursive
  CI_IMAGE:                        paritytech/ci-linux:production
  IMAGE_NAME:                      schildichat-web

.kubernetes-env:                   &kubernetes-env
  image:                           $CI_IMAGE
  tags:
    - kubernetes-parity-build

build-web:
  stage:                           build
  <<:                              *kubernetes-env
  script:
    - apt-get update
    - apt-get install -y vim curl git make gcc g++ python jq libsqlcipher-dev pkg-config libsecret-1-dev libarchive-tools openssl libssl-dev tcl gnupg
    - curl -sL https://deb.nodesource.com/setup_14.x | bash -
    - apt-get update
    - apt-get install -y nodejs
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
    - apt-get update
    - apt-get install yarn -y
    - make setup
    - make web
    - mkdir -p artifacts
    - cp ./element-web/dist/schildichat-web-$(cat ./element-web/webapp/version).tar.gz artifacts/schildichat-web.tar.gz
    - cp Dockerfile artifacts/
    - cp ./element-web/config.sample.json artifacts/
    - cp ./element-web/nginx/conf.d/default.conf artifacts/
    - cp ./element-web/webapp/version artifacts/
  artifacts:
    name:                          "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when:                          on_success
    expire_in:                     3 hours
    paths:
      - ./artifacts/

build-docker:
  stage:                           build-web
  <<:                              *kubernetes-env
  variables:
    GIT_STRATEGY:                  none
    DOCKERFILE:                    Dockerfile
  image:                           quay.io/buildah/stable
  script:
    - cd artifacts
    - tar xfvz schildichat-web.tar.gz
    - buildah bud
      --format=docker
      --build-arg VCS_REF="${CI_COMMIT_SHA}"
      --build-arg BUILD_DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
      --build-arg PROJECT_NAME="${CI_PROJECT_NAME}"
      --build-arg SCHILDI_DIR="schildichat-web-$(cat version)"
      --tag "$IMAGE_NAME:latest"
      --file "$DOCKERFILE" .
