
stages:
  - test
  - build
  - deploy

default:
  interruptible:                   true
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - api_failure

variables:
  GIT_SUBMODULE_STRATEGY:          recursive
  CI_IMAGE:                        paritytech/ci-linux:production

.kubernetes-env:                   &kubernetes-env
  image:                           $CI_IMAGE
  tags:
    - kubernetes-parity-build

build-web:
  stage:                           build
  <<:                              *kubernetes-env
  script:
    - apt-get update
    - apt-get install -y vim curl git make gcc g++ python jq libsqlcipher-dev pkg-config libsecret-1-dev libarchive-tools openssl libssl-dev tcl gnupg
    - curl -sL https://deb.nodesource.com/setup_14.x | bash -
    - apt-get update
    - apt-get install -y nodejs
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
    - apt-get update
    - apt-get install yarn -y
    - make setup
    - make web
    - mkdir -p artifacts
    - cp ./element-web/dist/schildichat-web-1.11.1-sc.0.test.1.tar.gz artifacts/
    - cp Dockerfile artifacts/
    - cp ./element-webconfig.sample.json artifacts/
    - cat ./element-web/webapp/version
  artifacts:
    name:                          "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when:                          on_success
    expire_in:                     3 hours
    paths:
      - ./artifacts/

build-docker:
  stage:                           build
  <<:                              *kubernetes-env
  variables:
    GIT_STRATEGY:                  none
  script:
    - ls -la artifacts
