ARG CONTAINER_IMAGE_DEBIAN
FROM ${CONTAINER_IMAGE_DEBIAN}:latest

RUN dpkg --add-architecture i386 && apt-get update && apt-get install --no-install-recommends -y \
    wine \
    wine32 \
    wine64 \
    libwine \
    libwine:i386 \
    fonts-wine \
    zip

WORKDIR /project