apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.fullname" . }}
  namespace: {{ template "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
        {{- with .Values.extraLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.json
          subPath: config.json
        env:
          {{- range $key, $value := .Values.common.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
          {{- end }}
        image: "{{ .Values.common.image.repository }}:{{ .Values.common.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        ports:
        {{- range $keys := .Values.common.service.ports }}
          - name: {{ .name }}
            containerPort: {{ .targetPort }}
            protocol: {{ .protocol }}
        {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: schildichat-web
