
common:
  fullnameOverride: "schildichat-web"
  serviceAccount:
    create: false
  image:
    repository: paritytech/schildichat-web
  service:
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns01
      kubernetes.io/ingress.class: traefik-internal
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
  # Enable after endpoint is created
  # livenessProbe:
  #   httpGet:
  #     path: /health
  #     port: 8000
  #     scheme: HTTP
  # readinessProbe:
  #   httpGet:
  #     path: /health
  #     port: 8000
  #     scheme: HTTP
